name: lsaBGC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - biopython=
  - pysam=
  - bioconda::bowtie2=2.3.4.3
  - bioconda::samtools=0.1.19
  - bioconda::mafft=
  - bioconda::mcl=
  - bioconda::pal2nal=
  - bioconda::fasttree=
  - bioconda::ete3
  - bioconda::mash=
  - conda-forge::r-base
  - conda-forge::r-pegas
  - conda-forge::r-ggplot2
  - conda-forge::r-cowplot
  - conda-forge::r-scatterpie