name: lsaBGC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8.10
  - pip=21.3.1
  - biopython=1.79
  - pysam=0.16.0.1
  - bioconda::bowtie2=2.4.4
  - bioconda::samtools=1.12
  - bioconda::mafft=7.487
  - bioconda::mcl=14.137
  - bioconda::pal2nal=14.1
  - bioconda::hmmer=3.3.2
  - bioconda::fasttree=2.1.10
  - conda-forge::ete3=3.1.2
  - bioconda::fastani=1.32
  - bioconda::mash=2.3
  - bioconda::diamond=2.0.8
  - conda-forge::r-base=4.0.3
  - conda-forge::r-ggplot2=3.3.5
  - conda-forge::r-cowplot=1.1.1
  - conda-forge::r-phytools=0.7_80
  - conda-forge::r-ape=5.5
  - conda-forge::r-scatterpie=0.1.6
  - conda-forge::r-dplyr=1.0.4
  - conda-forge::r-gggenes=0.4.1
  - bioconda::bioconductor-ggtree=2.4.0
  - conda-forge::r-ggalluvial=0.12.3
  - conda-forge::r-rvcheck=0.1.8
  - conda-forge::pomegranate=0.13.3
  - conda-forge::r-data.table=1.14.0
  - conda-forge::r-plyr=1.8.6
  - bioconda::comparem=0.1.2
  - bioconda::orthofinder=2.5.4
  - bioconda::prodigal=2.6.3
  - conda-forge::pandas=1.4.2
  - pip:
        - magus-msa= 0.1.0b2