[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lsaBGC"
authors = [{name = "Rauf Salamzade", email = "salamzader@gmail.com"}]
dynamic = ["version", "description"]