#!/usr/bin/env python3

### Program: LSABGC
### Author: Rauf Salamzade
### Kalan Lab
### UW Madison, Department of Medical Microbiology and Immunology

# BSD 3-Clause License
#
# Copyright (c) 2023, Kalan-Lab
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import sys
from lsaBGC import util

prog_set = set(['lsaBGC-Easy.py', 'lsaBGC-Euk-Easy.py'])

version = util.parseVersionFromSetupPy()

if __name__ == '__main__':
	args = sys.argv[1:]
	if len(args) == 0 or '--help' == args[0] or '-h' == args[0] or '-v' == args[0] or '--version' == args[0] or not (args[0] in prog_set):
		print("""	
		Program: LSABGC
		Version: %s""" % (version))
		print("""
		Author: Rauf Salamzade
		Affiliation: Kalan Lab, UW Madison, Department of Medical Microbiology and Immunology
	
		Wrapper for running 2 main workflows of the lsaBGC suite within Docker:
		
		- lsaBGC-Easy: Run lsaBGC-Easy for bacterial genomes from a common taxa (e.g. lineage, species or genus).
			* NOTE: Only works if you have genomes downloaded - e.g. GTDB automatic download part does not work within Docker!
			       The arguments: "-n None" will thus be appended to commands. 
			
		- lsaBGC-Euk-Easy: Run lsaBGC-Easy but specifically designed for fungal [small eukaryotic] genomes (experimental!)

		Usage example:
		./run_LSABGC.sh lsaBGC-Easy.py -n "None" -g Directory_of_Genomes_in_FASTA/ -o Results/ -c 10
		./run_LSABGC.sh lsaBGC-Euk-Easy.py -g Directory_of_Genomes_in_GenBank/ -o Results/ -c 10
		
		----------------------------------------------------------------------------------------------------------------------------
		KEY NOTES:
		----------------------------------------------------------------------------------------------------------------------------
		* For lsaBGC-Easy.py (but not lsaBGC-Euk-Easy.py), the -n "None" is currently required.
		* MEME (used in antiSMASH for CASSIS and RODEO) has been manually uninstalled in the antiSMASH conda environment within the 
		  lsaBGC Docker image because it requires a commercial license.
		* For arguments which you would provide quotes for if using the workflows directly, please manually add quotes preceeded by
		  a backslash from the printed Docker command and run it.
		  
		  Eg. running: 
		 
		 ./run_LSABGC.sh lsaBGC-Easy.py -n "None" -g Directory_of_Genomes_in_FASTA/ -o Results/ -c 10 -b -bo "--include_singletons"

		  will try to run lsaBGC-Easy and report some error because of the quoted arguments, but at the end print the Docker command:
		 
		  docker run --volume /home/salamzade/lsaBGC_Development/Test_v1.37:/home/input:ro \\
		             --volume /home/salamzade/lsaBGC_Development/Test_v1.37:/home/output:rw \\
			     --detach=false --rm --user=1010:1011 raufs/lsabgc:latest lsaBGC-Easy.py \\
			     -n None -g /home/input/Directory_of_Genomes_in_FASTA -o /home/output/Results \\
			     -c 10 -b -bo --include_singletons --docker_mode
		 
		  You can change this to the following (note the \" around values provided to -bo/--bigscape_options argument) and run it 
		  directly in shell:
		  
		  docker run --volume /home/salamzade/lsaBGC_Development/Test_v1.37:/home/input:ro \
		             --volume /home/salamzade/lsaBGC_Development/Test_v1.37:/home/output:rw \
			     --detach=false --rm --user=1010:1011 raufs/lsabgc:latest lsaBGC-Easy.py \
			     -n None -g /home/input/Directory_of_Genomes_in_FASTA -o /home/output/Results \
			     -c 10 -b -bo \"--include_singletons\" --docker_mode
		""")
	else:
		os.system(' '.join([x.replace('"', '\\"').replace("'", "\\'") for x in args]))
